name: Publish mcdu-dotnet NuGet Package

on:
    workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.x'

      - name: Restore dependencies
        run: dotnet restore mcdu-dotnet/mcdu-dotnet.csproj

      - name: Build
        run: dotnet build mcdu-dotnet/mcdu-dotnet.csproj --configuration Release --no-restore

      - name: Pack
        run: dotnet pack mcdu-dotnet/mcdu-dotnet.csproj --configuration Release --no-build --output ./nupkg

      - name: Push to NuGet
        run: dotnet nuget push ./nupkg/mcdu-dotnet*.nupkg --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json
